[package]
name = "VCTG"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql= "22.2.0"
rand = "0.8.4"
uuid = { version = "1.1.2", features = ["v4"] }
